### ISSUE TITLE
Incorrect encoding of int32 and int64 if communicating with google protobuf int32 and int64

### ISSUE THREAD

**Issue by TobiasPopetz** [eigenein/protobuf#103]
I found a problem in the encoding of int32 and int64.
In the [type definition](https://github.com/eigenein/protobuf/blob/master/pure_protobuf/types/__init__.py), int32 and int64 is set to uint32 and uint64.
This is not correct, because it doesn't allow negative values for intN.

According to the  ['Protocol Buffers' encoding of signed integers](https://developers.google.com/protocol-buffers/docs/encoding#signed-ints), intN values need to be encoded as two's complement.

Therefore, a new type definition of intN would be necessary, to guarantee the usage of negative intN values and also to guarantee the compatibility with standard google protobuf encoding.

I've created a small patch, which should solve the encoding problem for intN values.

```python
import struct

from google.protobuf import message
from itertools import count
from pure_protobuf import types as pureprototype
from pure_protobuf.dataclasses_ import SERIALIZERS
from pure_protobuf.serializers import Serializer
from pure_protobuf.enums import WireType
from pure_protobuf.io_ import IO
from pure_protobuf.serializers import signed_varint_serializer
from typing import NewType, Any, TypeVar, Type

pureprototype.int32 = NewType("int32", int)
pureprototype.int64 = NewType("int64", int)

T = TypeVar('T')


class IntNSerializer(Serializer):
    wire_type = WireType.VARINT
    local_int2byte = struct.Struct('>B').pack

    def __init__(self, sign_bit: int, mask: int, int_n: Type[T], int_n_range: int):
        self.sign_bit = sign_bit
        self.mask = mask,
        self.int_n = int_n
        self.int_n_range = int_n_range

    def validate(self, value: Any):
        signed_varint_serializer.validate(value)
        if not -self.int_n_range <= value <= self.int_n_range:
            raise ValueError("value is out of  integer range")

    def dump(self, value: Any, io: IO):
        if value < 0:
            value += (1 << 64)
        bits = value & 0x7f
        value >>= 7
        while value:
            io.write(self.local_int2byte(0x80 | bits))
            bits = value & 0x7f
            value >>= 7
        return io.write(self.local_int2byte(bits))

    def load(self, io: IO) -> Any:
        value = 0
        for shift in count(0, 7):
            (byte,) = io.read(1)
            value |= (byte & 0x7F) << shift
            if not byte & 0x80:
                value &= self.mask
                value = (value ^ self.sign_bit) - self.sign_bit
                return self.int_n(value)
            shift += 7
            if shift >= 64:
                raise message.DecodeError('Too many bytes when decoding varint.')
        return value


SERIALIZERS.update(
    {
        pureprototype.int32: IntNSerializer(
            sign_bit=1 << (32 - 1),
            mask=(1 << 32) - 1,
            int_n=pureprototype.int32,
            int_n_range=0x7FFFFFFF
        )
    }
)
SERIALIZERS.update(
    {
        pureprototype.int64: IntNSerializer(
            sign_bit=1 << (64 - 1),
            mask=(1 << 64) - 1,
            int_n=pureprototype.int64,
            int_n_range=0x7FFFFFFF_FFFFFFFF,
        )
    }
)

```

It would be good, if you can have a look into this patch and provide the `IntNSerializer` in one of the upcoming pure-protobuf releases.

Thanks a lot!

**Comment by eigenein** [comment]
Hi @TobiasPopetz,

Thanks for the report, you're correct. It appears that I've overlooked it. Impressive, how long the bug lived unnoticed 😃

I've just released the fix, could you try version `2.2.1`?

**Comment by TobiasPopetz** [comment]
Hi @eigenein,

thanks for the very quick response! :)

I've tried the update and there is still a problem with negative int32 values.

It seems, that google has a special processing for negative intN values.

In the [encoding description of signed ints](https://developers.google.com/protocol-buffers/docs/encoding#signed-ints) you can find this.
```
The intN types encode negative numbers as two's complement, which means that, as unsigned, 64-bit integers, they have their highest bit set. As a result, this means that all ten bytes must be used. For example, -2 is converted by protoscope into
````
The important point seems to be, that `negative values are always 10 bytes long`, independent if they are int32 or int64.

This you can also see in the protobuf code.
Here int32 and int64 are using the same encoder.
See https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/encoder.py#L625

If you have a deeper look, you can see that the encoder always makes this operation `value += (1 << 64)` if negative values are given.
See https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/encoder.py#L394

The SignedVarintSize is calculated here.
See https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/encoder.py#L94 

It would be very good if you can make these adjustments.

Thanks a lot!

**Comment by eigenein** [comment]
Hi @TobiasPopetz,

Indeed, they use the same encoder. 🤔 Seems that I did more work than was needed in the first place. I will fix it shortly!

**Comment by eigenein** [comment]
👋 @TobiasPopetz 

Sorry for the delay. Could you try the `2.2.2`?

**Comment by TobiasPopetz** [comment]
@eigenein Now it looks good on my side! 👍🏼 
Compatibility between protobuf intN and pure-protobuf intN is given in both directions.  
Thanks for the quick fix! 🥇
